Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "MathieuS" do |control|
    control.vm.hostname = "MathieuS"
    control.vm.network "private_network", ip: "192.168.122.110"
    control.vm.synced_folder "./vagrant", "/mnt", create: true, nfs_udp: false
    control.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  config.vm.provision "ansible" do |a|
    a.playbook = "ansible/main.yml"
    a.groups = {
      "servers" => ["MathieuS"],
    }
    a.extra_vars = {
      node_ip: "192.168.122.110",
      apps: ["app1", "app2", "app3"]
    }
    a.limit = "all"  
    a.compatibility_mode = "2.0"
  end
end
