Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "MathieuS" do |control|
    control.vm.hostname = "MathieuS"
    control.vm.network "private_network", ip: "192.168.122.110"
    control.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    
    control.vm.provision :shell, path: "k3s-install.sh"
    control.vm.provision :shell, path: "k3s-deploy.sh"
  end
end
