apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  selector:
    matchLabels: { app: app2 }
  template:
    metadata:
      labels: { app: app2 }
    spec:
      containers:
      - name: app2
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080