NODE_ROLES = ["MathieuS","MathieuSW"]
NODE_BOXES = ['bento/ubuntu-24.04', 'bento/ubuntu-24.04']
NODE_CPUS = 1
NODE_MEMORY = 512
NETWORK_PREFIX = "192.168.122"

def provision(vm, role, node_num)
  vm.box = NODE_BOXES[node_num]
  vm.hostname = role

  node_ip = "#{NETWORK_PREFIX}.#{100+node_num}"

  vm.network "private_network", ip: node_ip, netmask: "255.255.255.0"

  vm.provision "ansible", run: 'once' do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "playbooks/site.yml"
    ansible.groups = {
      "server" => NODE_ROLES.grep(/^S$/),
      "agent" => NODE_ROLES.grep(/^SW$/),
      "k3s_cluster:children" => ["server", "agent"],
    }
    ansible.extra_vars = {
      k3s_version: "v1.31.12+k3s1",
      api_endpoint: "#{NETWORK_PREFIX}.100",
      token: "myvagrant",
      extra_server_args: "--node-external-ip #{node_ip} --flannel-iface virbr0", 
      extra_agent_args: "--node-external-ip #{node_ip} --flannel-iface virbr0",
    }
  end
end

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt" do |v|
    v.cpus = NODE_CPUS
    v.memory = NODE_MEMORY
  end
  
  NODE_ROLES.each_with_index do |name, i|
    config.vm.define name do |node|
      provision(node.vm, name, i)
    end
  end
end